### ISSUE TITLE
Yr integragtion is no longer in homeassistant

### ISSUE THREAD

**Issue by pellle87** [Gnaget2/Car-Heater-Package#12]
i have tried to get it to work with met integration which i seem to have accomplished but my groups wont load when i got this package so i tried migrate the groups section from your yaml to groups.yaml which didnt work either.

Is it possible to get an update to this awesome package?

**Comment by sunkan85** [comment]
this might work. I have not tested it
[heater fix.txt](https://github.com/Gnaget2/Car-Heater-Package/files/5775679/heater.fix.txt)

**Comment by pellle87** [comment]
Cool, ill try it out tonight :)

**Comment by sunkan85** [comment]
you have to change to your switch.  please confirm if it works so others can use it

**Comment by pellle87** [comment]
Ok so i changed:
```
  heater_on:
    sequence:
    - service: light.turn_on
      entity_id: light.motorvarmare
    - service: homeassistant.turn_on
      entity_id: automation.heater_off
```
  To:
```
  heater_on:
    sequence:
    - service: switch.turn_on
      entity_id: switch.driveway_socket
    - service: homeassistant.turn_on
      entity_id: automation.heater_off
```

and changed 
```
  - platform: template
    sensors:
      heater_outside_temp:
        friendly_name: 'Utomhus temperatur'
        value_template: "{{ states('outside_temperature') }}"  ## Change to local temperature source
```
To:
```
  - platform: template
    sensors:
      heater_outside_temp:
        friendly_name: 'Utomhus temperatur'
        value_template: "{{ states('weather_temperature') }}"  ## Change to local temperature source
```

I get no errors, gonna set timer tonight and see tomorrow if it has started as supposed :)

**Comment by pellle87** [comment]
Update: the switch hadnt been activated this morning
Noticing sensor.heater_outside_temp reports unknown as value, so the problem is probably there

**Comment by pellle87** [comment]
Changed:
```
sensor:

  - platform: template
    sensors:
      outside_temperature:
        friendly_name: "Outside Temperature"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('weather.home', 'temperature') }}"
```
To:

```
sensor:

  - platform: template
    sensors:
      outside_temperature:
        friendly_name: "Outside Temperature"
        unit_of_measurement: '°C'
        value_template: "{{ states('sensor.weather_temperature') }}"
```
Now i get the temp from sensor.outside_temperature so hopefully it will work, also i had missed changing 


```
# Turns the heater off when leaving time is reached
  - alias: "heater off"
    initial_state: false
    trigger:
     - platform: time_pattern
       minutes: '/5'
       seconds: 2
    condition:
      - condition: template
        value_template: "{{ ((as_timestamp(now()) | int | timestamp_custom('%H:%M')) == states('sensor.engineheaterofftime')) }}"
    action:
       **- service: light.turn_off
         entity_id: light.motorvarmare**
       - service: homeassistant.turn_off
         entity_id: automation.heater_off
```
