### ISSUE TITLE
Group properties deprecated

### ISSUE THREAD

**Issue by theavier** [Gnaget2/Car-Heater-Package#13]
Great solution! 
I had some problem getting it working though, took some time to find that certain properties on groups seems to be deprecated.
I'm noting this here so other might be save some time. 
Link to page with info about breaking changes
https://www.home-assistant.io/blog/2020/03/18/release-107/#breaking-changes
"
Groups - Groups are NOT being removed, but the configuration options, services, and service options related to the (previously deprecated and now removed) States UI are now removed in this release. This includes:
The view and control configuration options for a group.
The group.set_visibility service call
The control, visible, view options on the group.set service call
Please ensure your configuration and automations do not use these anymore
"
By commenting group control and view I got HA to stop complaining and it works as expected now.
Not sure if this breaks something else, kind hard to find documentation for certain features in HA.
```
# Group section
group:
  heater_view:
    #view: yes
    name: heter
    icon: mdi:radiator
    entities:
      - group.heater
# option to show the automations and scripts that controls the heater 
#      - group.heater_controls

  heater:
    #control: hidden
    name: "Motorvärmare"
    entities:
      - sensor.departuretime
#      - sensor.heater_start_time
      - input_number.heater_hour
      - input_number.heater_minutes
      - sensor.heater_outside_temp
      - switch.carheater
      - input_boolean.heaterstatus
      - input_boolean.heaterweekday
  ```
