### ISSUE TITLE
check every hour instead of just 02:00

### ISSUE THREAD

**Issue by pellle87** [Gnaget2/Car-Heater-Package#17]
So current code says:
```
# activates the automations that will trigger the heater depending on temp if the function is activated
  - alias: "heater enabled"
    initial_state: true
    trigger:
      platform: time
      at: 02:00
    condition:
       - condition: state
         entity_id: input_boolean.heaterstatus
         state: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: automation.heater_minus_20, automation.heater_minus_10, automation.heater_plus_1, automation.heater_plus_5
```
Wouldnt it be possible to change it like this:
```
# activates the automations that will trigger the heater depending on temp if the function is activated
  - alias: "heater enabled"
    initial_state: true
    trigger:
      platform: time_pattern
      Hours: '/1'
    condition:
       - condition: state
         entity_id: input_boolean.heaterstatus
         state: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: automation.heater_minus_20, automation.heater_minus_10, automation.heater_plus_1, automation.heater_plus_5
```
So that it checks every hour? i would want that because usally i got heater set on 07:30 and then i go and drop off kids - go home work and has set the heater time to 16:00 but the heater hasnt started (obviously)
Or am i thinking wrong here?
